### ISSUE TITLE
Improve forms

### ISSUE THREAD

**Issue by bcalou** [lucrampro/local-money#1]
Attention, plusieurs problèmes important à corriger sur les formulaires :

- type inadapté (text au lieu de email par exemple)
- absence de <label> lié à l'input grâce aux attributs for/id
- absence d'élément <form> obligatoire pour la validation au clavier / accessibilité

Les forms sont les parties les plus importantes d'une appli, à soigner absolument !

**Comment by nekocheik** [comment]
@bcalou 
c'est fait,
nous pouvons maintenant valider, le formulaire avec la touche entrer.
Les inputs sont maintenant relier avec leur label.
Les types des inputs ont été mis pour améliorer l'expérience utilisateur.

**Comment by bcalou** [comment]
Ok super. Je te laisse fermer l'issue :)
