### ISSUE TITLE
Better names for steps

### ISSUE THREAD

**Issue by bcalou** [lucrampro/local-money#2]
Très bonne idée de faire un tunnel de cette façon (inscription.js).
Pour que ce soit plus maintenable, je vous conseille de donner un vrai nom au step, pas stepOne, stepTwo. 
Cela vous permettra de plus facilement savoir ce que contient chaque step, et surtout de pouvoir en ajouter/enlever facilement.

**Comment by bcalou** [comment]
Par contre, attention à rester sur de l'anglais (! = TypeDeCompte)
;)

**Comment by lucrampro** [comment]
ok je vais tout refaire en anglais :)

**Comment by nekocheik** [comment]
@bcalou 
C'est fait, vous pouvez vérifier.

**Comment by bcalou** [comment]
Ok pour moi ! Je vous laisse fermer en temps voulu
